apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
type: Opaque
stringData:
  root_password: "maria@clave$1234"
  user: "grupob10"               
  user_password: "b10clave$1234"    
  database: "concesionario"     
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: concesionario-sql
data:
  Concesionario.sql: |
    CREATE DATABASE IF NOT EXISTS concesionario;
    USE concesionario;
    CREATE TABLE coches(
        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        nombre VARCHAR(255) NOT NULL,
        descripcion VARCHAR(255) NOT NULL,
        precio DECIMAL(9,2) NOT NULL,
      foto VARCHAR(255)
    );
    CREATE TABLE comentarios(
        id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
        usuario VARCHAR(255) NOT NULL,
        descripcion VARCHAR(255) NOT NULL
    );
    CREATE TABLE usuarios(
      usuario VARCHAR(100) NOT NULL PRIMARY KEY,
        clave VARCHAR(255) NOT NULL,
        perfil VARCHAR(100) NOT NULL
    );
    INSERT INTO `usuarios` (`usuario`, `clave`, `perfil`) VALUES ('root','1234', 'admin');

    CREATE USER 'grupob10'@'%' IDENTIFIED BY 'b10clave$1234';
    GRANT ALL PRIVILEGES ON concesionario.* TO 'grupob10'@'%';
    FLUSH PRIVILEGES;