apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-waf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-waf
  template:
    metadata:
      labels:
        app: apache-waf
    spec:
      containers:
        - name: apache-waf
          image: francesdbz18/apacheb10:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: apache-waf
spec:
  type: NodePort
  selector:
    app: apache-waf
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30710
